2020/09/30 12:06:49 [error] 6#6: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.240.1, server: localhost, request: "GET / HTTP/1.1", upstream: "fastcgi://192.168.240.4:9000", host: "localhost"
2020/09/30 12:06:51 [error] 6#6: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.240.1, server: localhost, request: "GET / HTTP/1.1", upstream: "fastcgi://192.168.240.4:9000", host: "localhost"
2020/09/30 12:06:52 [error] 6#6: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.240.1, server: localhost, request: "GET / HTTP/1.1", upstream: "fastcgi://192.168.240.4:9000", host: "localhost"
2020/09/30 12:06:52 [error] 6#6: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.240.1, server: localhost, request: "GET / HTTP/1.1", upstream: "fastcgi://192.168.240.4:9000", host: "localhost"
2020/09/30 12:06:53 [error] 6#6: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.240.1, server: localhost, request: "GET / HTTP/1.1", upstream: "fastcgi://192.168.240.4:9000", host: "localhost"
2020/09/30 12:06:53 [error] 6#6: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.240.1, server: localhost, request: "GET / HTTP/1.1", upstream: "fastcgi://192.168.240.4:9000", host: "localhost"
2020/09/30 12:06:53 [error] 6#6: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.240.1, server: localhost, request: "GET / HTTP/1.1", upstream: "fastcgi://192.168.240.4:9000", host: "localhost"
2020/09/30 12:06:53 [error] 6#6: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.240.1, server: localhost, request: "GET / HTTP/1.1", upstream: "fastcgi://192.168.240.4:9000", host: "localhost"
2020/09/30 12:07:08 [error] 6#6: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.240.1, server: localhost, request: "GET / HTTP/1.1", upstream: "fastcgi://192.168.240.4:9000", host: "localhost"
2020/09/30 12:09:33 [error] 6#6: *2 connect() failed (111: Connection refused) while connecting to upstream, client: 172.18.0.1, server: localhost, request: "GET / HTTP/1.1", upstream: "fastcgi://172.18.0.4:9000", host: "localhost"
2020/09/30 12:09:35 [error] 6#6: *2 connect() failed (111: Connection refused) while connecting to upstream, client: 172.18.0.1, server: localhost, request: "GET / HTTP/1.1", upstream: "fastcgi://172.18.0.4:9000", host: "localhost"
2020/09/30 12:09:35 [error] 6#6: *2 connect() failed (111: Connection refused) while connecting to upstream, client: 172.18.0.1, server: localhost, request: "GET /favicon.ico HTTP/1.1", upstream: "fastcgi://172.18.0.4:9000", host: "localhost", referrer: "http://localhost/"
2020/09/30 12:11:53 [error] 6#6: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.19.0.1, server: localhost, request: "GET / HTTP/1.1", upstream: "fastcgi://172.19.0.4:9000", host: "localhost"
2020/09/30 12:11:53 [error] 6#6: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.19.0.1, server: localhost, request: "GET /favicon.ico HTTP/1.1", upstream: "fastcgi://172.19.0.4:9000", host: "localhost", referrer: "http://localhost/"
2020/09/30 12:26:15 [error] 6#6: *8 connect() failed (111: Connection refused) while connecting to upstream, client: 172.19.0.1, server: localhost, request: "GET / HTTP/1.1", upstream: "fastcgi://172.19.0.4:9000", host: "localhost"
2020/09/30 12:26:15 [error] 6#6: *8 connect() failed (111: Connection refused) while connecting to upstream, client: 172.19.0.1, server: localhost, request: "GET /favicon.ico HTTP/1.1", upstream: "fastcgi://172.19.0.4:9000", host: "localhost", referrer: "http://localhost/"
